apiVersion: v1
kind: ConfigMap
metadata:
  name: urls-internas
  namespace: bienal-backend
data:
  FRONTEND_URL: "http://frontend.example.com"
  API_GATEWAY_URL: "http://api-gateway.bienal-backend.svc.cluster.local"
  SERVICE_GESTION_ESCULTORES_URL: "http://gestion-escultores.bienal-backend.svc.cluster.local"
  SERVICE_GESTION_ESCULTURAS_URL: "http://gestion-esculturas.bienal-backend.svc.cluster.local"
  SERVICE_GESTION_EVENTOS_URL: "http://gestion-eventos.bienal-backend.svc.cluster.local"
  SERVICE_REGISTRO_VOTOS_URL: "http://registro-votos.bienal-backend.svc.cluster.local"
  SERVICE_GENERADOR_QR_URL: "http://generador-qr.bienal-backend.svc.cluster.local"
  SERVICE_AUTENTICACION_URL: "http://autenticacion.bienal-backend.svc.cluster.local"
--- # Api gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: stefanomerinoderui/bienal-backend:api_gateway
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: FRONTEND_URL
        - name: API_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: API_GATEWAY_URL
        - name: SERVICE_GESTION_ESCULTORES_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: SERVICE_GESTION_ESCULTORES_URL
        - name: SERVICE_GESTION_ESCULTURAS_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: SERVICE_GESTION_ESCULTURAS_URL
        - name: SERVICE_GESTION_EVENTOS_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: SERVICE_GESTION_EVENTOS_URL
        - name: SERVICE_REGISTRO_VOTOS_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: SERVICE_REGISTRO_VOTOS_URL
        - name: SERVICE_GENERADOR_QR_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: SERVICE_GENERADOR_QR_URL
        - name: SERVICE_AUTENTICACION_URL
          valueFrom:
            configMapKeyRef:
              name: urls-internas
              key: SERVICE_AUTENTICACION_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: bienal-backend
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Permite que el tráfico de salida sea accesible desde Internet
--- # Gestion escultores
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-escultores
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-escultores
  template:
    metadata:
      labels:
        app: gestion-escultores
    spec:
      containers:
      - name: gestion-escultores-container
        image: stefanomerinoderui/bienal-backend:gestion_escultores
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-escultores
  namespace: bienal-backend
spec:
  selector:
    app: gestion-escultores
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster
--- # Gestion esculturas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-esculturas
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-esculturas
  template:
    metadata:
      labels:
        app: gestion-esculturas
    spec:
      containers:
      - name: gestion-esculturas-container
        image: stefanomerinoderui/bienal-backend:gestion_esculturas
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-esculturas
  namespace: bienal-backend
spec:
  selector:
    app: gestion-esculturas
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster
--- # Gestion eventos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-eventos
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-eventos
  template:
    metadata:
      labels:
        app: gestion-eventos
    spec:
      containers:
      - name: gestion-eventos-container
        image: stefanomerinoderui/bienal-backend:gestion_eventos
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-eventos
  namespace: bienal-backend
spec:
  selector:
    app: gestion-eventos
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster
--- # Generador Qr
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generador-qr
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generador-qr
  template:
    metadata:
      labels:
        app: generador-qr
    spec:
      containers:
      - name: generador-qr-container
        image: stefanomerinoderui/bienal-backend:generadorQr
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
---
apiVersion: v1
kind: Service
metadata:
  name: generador-qr
  namespace: bienal-backend
spec:
  selector:
    app: generador-qr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster
--- # Registro de votos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registro-votos
  namespace: bienal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registro-votos
  template:
    metadata:
      labels:
        app: registro-votos
    spec:
      containers:
      - name: registro-votos-container
        image: stefanomerinoderui/bienal-backend:registro_votos
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri    # Nombre del Secret
              key: MONGODB_URI   # Clave en el Secret
---
apiVersion: v1
kind: Service
metadata:
  name: registro-votos
  namespace: bienal-backend
spec:
  selector:
    app: registro-votos
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Permite que el tráfico de salida sea accesible desde el cluster
--- # Servicio de autenticacion