services:
  gestion_escultores:
    build:
      context: ./../ModuloGestion/ServicioGestionEscultores
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:gestion_escultores
    ports:
      - "80:80"
  gestion_esculturas:
    build:
      context: ./../ModuloGestion/ServicioGestionEsculturas
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:gestion_esculturas
    ports:
      - "80:80"
  gestion_eventos:
    build:
      context: ./../ModuloGestion/ServicioGestionEventos
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:gestion_eventos
    ports:
      - "80:80"
  autenticacion:
    build:
      context: ./../ModuloVotYVal/SubmoduloAuth
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:autenticacion
    ports:
      - "80:80"
  registro_votos:
    build:
      context: ./../ModuloVotYVal/SubmoduloRegistroVotos
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:registro_votos
    ports:
      - "80:80"
  validacion_votos:
    build:
      context: ./../ModuloVotYVal/SubModuloValidVotos
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:validacion_votos
    ports:
      - "80:80"
  visualizacion_escultores:
    build:
      context: ./../visualizacionEscultores
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:visualizacion_escultores
    ports:
      - "80:80"
  visualizacion_esculturas:
    build:
      context: ./../visualizacionEsculturas
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:visualizacion_esculturas
    ports:
      - "80:80"
  visualizacion_eventos:
    build:
      context: ./../visualizacionEventos
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:visualizacion_eventos
    ports:
      - "80:80"
#  generadorQR:
#    build:
#      context: ./../SevicioQr
#      dockerfile: docker/Dockerfile
#      args:
#        external-port: 80
#    image: stefanomerinoderui/bienal-backend:generadorQ
#    ports:
#      - "80:80"
  votaciones:
    build:
      context: ./../votaciones
      dockerfile: docker/Dockerfile
      args:
        external-port: 80
    image: stefanomerinoderui/bienal-backend:votaciones
    ports:
      - "80:80"
#  api_gateway:
#    build:
#      context: ./../apiGateway
#      dockerfile: docker/Dockerfile
#      args:
#          external-port: 80
#    image: stefanomerinoderui/bienal-backend:api_gateway
#    ports:
#      - "80:80"