http:
  port: ${process.env.PORT:-80} # default port 80
#admin:
#  port: 9876
#  host: localhost
apiEndpoints:
  gestion_escultores:
    paths: "/api/escultores*"
    methods: ["PUT", "POST", "DELETE"]  
  gestion_esculturas:
    paths: "/api/esculturas*"
    methods: ["PUT", "POST", "DELETE"]  
  gestion_eventos:
    paths: "/api/eventos*"
    methods: ["PUT", "POST", "DELETE"]  
  autenticacion:
    paths: "/api/autenticacion*"
  registro_votos:
    paths: "/api/registro_votos*"
  validacion_votos:
    paths: "/api/validacion_votos*"
  visualizacion_escultores:
    paths: "/api/escultores"
    methods: ["GET"]
  visualizacion_esculturas:
    paths: "/api/esculturas"
    methods: ["GET"]
  visualizacion_eventos:
    paths: "/api/eventos"
    methods: ["GET"]
  votacion:
    paths: "/api/votacion*"
---
serviceEndpoints:
  gestion_escultores:
    url: ${process.env.SERVICE_GESTION_ESCULTORES_URL}
  gestion_esculturas:
    url: ${process.env.SERVICE_GESTION_ESCULTURAS_URL}
  gestion_eventos:
    url: ${process.env.SERVICE_GESTION_EVENTOS_URL}
  autenticacion:
    url: ${process.env.SERVICE_AUTENTICACION_URL}
  registro_votos:
    url: ${process.env.SERVICE_REGISTRO_VOTOS_URL}
  validacion_votos:
    url: ${process.env.SERVICE_VALIDACION_VOTOS_URL}
  visualizacion_escultores:
    url: ${process.env.SERVICE_VISUALIZACION_ESCULTORES_URL}
  visualizacion_esculturas:
    url: ${process.env.SERVICE_VISUALIZACION_ESCULTURAS_URL}
  visualizacion_eventos:
    url: ${process.env.SERVICE_VISUALIZACION_EVENTOS_URL}
  votacion:
    url: ${process.env.SERVICE_VOTACION_URL}
---
policies:
  - proxy:
pipelines:
  escultoresPipeline:
    apiEndpoints:
      - escultores
    policies:
      - proxy:
          - action:
              serviceEndpoint: gestion_escultores
              changeOrigin: true
#changeOrigin:
# Si tu API Gateway recibe una solicitud a http://mi-gateway.com/api/escultores, y el serviceEndpoint para esta solicitud apunta a 
# http://servicio-escultores.com, al usar changeOrigin: true, el encabezado Host de la solicitud será servicio-escultores.com
# en lugar de mi-gateway.com. Esto permite que el backend interprete la solicitud como si estuviera directamente dirigida a él.
  esculturasPipeline:
    apiEndpoints:
      - esculturas
    policies:
      - proxy:
          - action:
              serviceEndpoint: gestion_esculturas
              changeOrigin: true

  eventosPipeline:
    apiEndpoints:
      - eventos
    policies:
      - proxy:
          - action:
              serviceEndpoint: gestion_eventos
              changeOrigin: true

  autenticacionPipeline:
    apiEndpoints:
      - autenticacion
    policies:
      - proxy:
          - action:
              serviceEndpoint: autenticacion
              changeOrigin: true

  registroVotosPipeline:
    apiEndpoints:
      - registro_votos
    policies:
      - proxy:
          - action:
              serviceEndpoint: registro_votos
              changeOrigin: true

  validacionVotosPipeline:
    apiEndpoints:
      - validacion_votos
    policies:
      - proxy:
          - action:
              serviceEndpoint: validacion_votos
              changeOrigin: true

  visualizacionEscultoresPipeline:
    apiEndpoints:
      - visualizacion_escultores
    policies:
      - proxy:
          - action:
              serviceEndpoint: visualizacion_escultores
              changeOrigin: true

  visualizacionEsculturasPipeline:
    apiEndpoints:
      - visualizacion_esculturas
    policies:
      - proxy:
          - action:
              serviceEndpoint: visualizacion_esculturas
              changeOrigin: true

  visualizacionEventosPipeline:
    apiEndpoints:
      - visualizacion_eventos
    policies:
      - proxy:
          - action:
              serviceEndpoint: visualizacion_eventos
              changeOrigin: true

  votacionPipeline:
    apiEndpoints:
      - votacion
    policies:
      - proxy:
          - action:
              serviceEndpoint: votacion
              changeOrigin: true
---
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
