http:
  port: ${HTTP_PORT:-80} # default port 80
#admin:
#  port: 9876
#  host: localhost
apiEndpoints:
  gestion_escultores:
    paths: "/api/escultores*"
    methods: ["PUT", "POST", "DELETE"]
  gestion_esculturas:
    paths: "/api/esculturas*"
    methods: ["PUT", "POST", "DELETE"]
  gestion_eventos:
    paths: "/api/eventos*"
    methods: ["PUT", "POST", "DELETE"]
  autenticacion:
    paths: "/api/autenticacion*"
  registro_votos:
    paths: "/api/registro_votos*"
  validacion_votos:
    paths: "/api/validacion_votos*"
  visualizacion_escultores:
    paths: "/api/escultores"
    methods: ["GET"]
  visualizacion_esculturas:
    paths: "/api/esculturas"
    methods: ["GET"]
  visualizacion_eventos:
    paths: "/api/eventos"
    methods: ["GET"]
  votacion:
    paths: "/api/votacion*"

serviceEndpoints:
  gestion_escultores:
    url: ${process.env.SERVICE_GESTION_ESCULTORES_URL}
  gestion_esculturas:
    url: ${process.env.SERVICE_GESTION_ESCULTURAS_URL}
  gestion_eventos:
    url: ${process.env.SERVICE_GESTION_EVENTOS_URL}
  autenticacion:
    url: ${process.env.SERVICE_AUTENTICACION_URL}
  registro_votos:
    url: ${process.env.SERVICE_REGISTRO_VOTOS_URL}
  validacion_votos:
    url: ${process.env.SERVICE_VALIDACION_VOTOS_URL}
  generador_qr:
    url: ${process.env.SERVICE_GENERADOR_QR_URL}

policies:
  - proxy:

pipelines:
  escultoresPipeline:
    apiEndpoints:
      - gestion_escultores
    policies:
      - proxy:
          - action:
              serviceEndpoint: gestion_escultores
              changeOrigin: true

  esculturasPipeline:
    apiEndpoints:
      - gestion_esculturas
    policies:
      - proxy:
          - action:
              serviceEndpoint: gestion_esculturas
              changeOrigin: true

  eventosPipeline:
    apiEndpoints:
      - gestion_eventos
    policies:
      - proxy:
          - action:
              serviceEndpoint: gestion_eventos
              changeOrigin: true

  autenticacionPipeline:
    apiEndpoints:
      - autenticacion
    policies:
      - proxy:
          - action:
              serviceEndpoint: autenticacion
              changeOrigin: true

  registroVotosPipeline:
    apiEndpoints:
      - registro_votos
    policies:
      - proxy:
          - action:
              serviceEndpoint: registro_votos
              changeOrigin: true

  validacionVotosPipeline:
    apiEndpoints:
      - validacion_votos
    policies:
      - proxy:
          - action:
              serviceEndpoint: validacion_votos
              changeOrigin: true

  generadorQrPipeline:
    apiEndpoints:
      - generador_qr
    policies:
      - proxy:
          - action:
              serviceEndpoint: generador_qr
              changeOrigin: true

  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true